workflows:
  react-native-android:
    name: hälsoPilot Android
    max_build_duration: 60
    environment:
      node: 18.17.0
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install Expo CLI
        script: npm install -g expo-cli eas-cli
      - name: Build Android APK
        script: |
          npx expo prebuild --platform android --clean
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
